### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by lfarah** [amosavian/FileProvider#1]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by amosavian** [comment]
I'm waiting for Swift Package Manager 😆 But I will add when I have free time

**Comment by amosavian** [comment]
@lfarah Added tnx

**Comment by lfarah** [comment]
You're welcome! 😄
