### ISSUE TITLE
FileProviderOperations create(file:at:contents:) could use a String instead of a FileObject for the file parameter.

### ISSUE THREAD

**Issue by RndmTsk** [amosavian/FileProvider#10]
After reviewing `create(file:at:contents:)` it seems that a `String` could be used instead of a `FileObject` as the name/path are the only parts used (the path comes from the `at` parameter).

Changing this would also bring it more in line with `create(folder:at:completionHandler)` where a nearly empty `FileObject` is *not* required.

Were there future plans around using the information from the `FileObject` inside `create(file:at:contents)`?

```
public func create(file fileAttribs: FileObject, at path: String, contents data: Data?, completionHandler: SimpleCompletionHandler) -> OperationHandle?

// vs. //

public func create(folder folderName: String, at atPath: String, completionHandler: SimpleCompletionHandler) -> OperationHandle?
```

**Comment by amosavian** [comment]
Indeed my intension was allowing user to determine file properties such as Readonly. You are right I will change the function.
