### ISSUE TITLE
HELP WANTED - How to stop execution when error occurs from multi upload

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#101]
You can click [here](https://my.pcloud.com/publink/show?code=XZBU5B7ZBKxlTH75ba4HLPHWaaqrQVkBbAOy) to download the code. Whether set a wrong webdav URL (`https://webdav.pcloud` instead `https://webdav.pcloud.com`), the error message shows multiple windows when trying to upload multiple photos but it doesn't stop the execution of the program. So, how do I stop the execution when error occurs  from multi upload? Could you please suggest how to edit the code so that the program stops when it finds an error?

Moreover, I still do not understand how to handle the GCD.

Thanks for the suggestions you can give me.

**Comment by CPiersigilli** [comment]
With reference to the code downloadable from [here](https://my.pcloud.com/publink/show?code=XZBU5B7ZBKxlTH75ba4HLPHWaaqrQVkBbAOy) (same as before).
`FIRST PROBLEM`
To upload a file, for example in `test` folder, which I do not know if it exists, I first have to create it with your `create (folder:` and then upload with your `writeContents (path:`, as in `func upLoadMultiPhoto (` in `WebdavHelper.swift`. If I insert the wrong server url, the procedure does not stop at `create (folder:` but it continues providing me with two alerts and not just one. How can I modify the `func upLoadMultiPhoto (`in `WebdavHelper.swift` to make it work properly?
`SECOND PROBLEM`
You could tell me how to change my test code `FilesProvider_test` to add every returned progress to it as child, using `fractionCompleted` to find out the percentage or assign it to `UIProgressView ().observProgress` to show progress to the user?
`THIRD PROBLEM`
I found that trying to upload a file from `func upLoadMultiPhoto (` when the connection is very slow, the procedure does not stop. Is it possible to block the upload from code? Which function should I use?

Thanks for the suggestions you can give me.

**Comment by amosavian** [comment]
Frankly I really don't enough time to study an undocumented code with few hundred LOC, please ask straight with small samples.

Please read [Apple documentation](https://developer.apple.com/documentation/foundation/progress) to find how `Progress` works.

To cancel an operation, you can call `.cancel()` method on returned progress object.

**Comment by CPiersigilli** [comment]
Ok.  As you requested me, I will give you small examples.
Thank you.
