### ISSUE TITLE
FTPFileProvider protocol exception? 

### ISSUE THREAD

**Issue by JackPearse** [amosavian/FileProvider#103]
Hi amosavian,

first of all I would like to thank you! This library is awesome. 

However, I think I found an issue which may happen with server responses. Long time ago I developed a small http-server and discovered that not all servers are "literally" following the specification. Sometimes there is whitespaces missing or just a dash inserted so that the parser gets confused. I am not sure if this is the case here. Maybe you could have a look at this:

In the 

  `func ftpRetrieve(_ task: filePath: from position: length: onTask:  onProgress: completionHandler:)`

the framework calls the closure

```
{ (response, error) in
                                        
           do {
                        if let error = error {
                            throw error
                        }
                        
                        guard let response = response else {
                            throw self.urlError(filePath, code: .cannotParseResponse)
                        }
                        
                        if !(response.hasPrefix("1") || response.hasPrefix("2")) {
                            throw FileProviderFTPError(message: response)
                        }
  
     
                    } catch {
                        self.dispatch_queue.async {
                            completionHandler(error)
                        }
                 }
```

I was curious what happened, because "officially" the connection timed out. I did a debug-dump of the variable `response`. The result was:

`200 Type set to I\r\n350 Restarting at 0. Send STORE or RETRIEVE to initiate transfer\r\n227 Entering Passive Mode (212,227,24,12,218,208).`

So it looks like the server works properly and accepts the calls from your framework. Is this probably a case which could be covered by this framework?

Or did I misunderstand how it works? Because I assume the callback is correct. But no data is being transmitted, the frameworks stops with a timeout.

**Comment by amosavian** [comment]
I don't know what's your point exactly. But timeout is handled by these three lines in the closure you mentioned:

```swift
if let error = error {
    throw error
}
```

**Comment by JackPearse** [comment]
Hi amosavian,

thank you for your quick reply. Yes, I was a little bit sloppy in my text, sorry for that. You are right, the control connection works perfectly, but the data connection doesn't work and times out. 

I hie read similar complaints in other issues listed here. Probably you could help me pointing out where the parallel data connection is handled in your code, then I can do some debugging. Maybe there is some specialties with some servers, why you can't recreate that error. 

I already tried .extendedPassive. But in that case absolutely nothing happens. Only .passive works for me. 

Can you tell me where in the code the data transfer is initiated? I am sometimes confused while searching in that code. It became a really complex framework. If I find the problem, this could probably solve some of the other open issues.

**Comment by amosavian** [comment]
`ftpDataConnect()` method establishes data connection.

**Comment by JackPearse** [comment]
Cool, thank you. I will do some debug traces and let you know what I can find.

**Comment by amosavian** [comment]
@JackPearse I have the same issue in my test. The problem is not establishing data connection. I think it's related to locks. I will address them

**Comment by JackPearse** [comment]
Now I have a more detailed insight. However, I still don't understand why this happens.
This is the log I could trace

```
copyItem -> ftpLogin(task) closure: starting ftpDownload on task OK
copyItem -> ftpLogin(task) -> ftpDownload(...) OK
copyItem -> ftpLogin(task) -> ftpDownload(...) starting ftpRetrieve
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) was entered
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) -> attributesOfItem(...) was called
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) -> attributesOfItem(...) -> ftpLogin(taks) -> completion hanlder was called
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) -> attributesOfItem(...) -> ftpLogin(taks)  command: LIST /testfolder/Testfile.json
(ftp client waits for 20 seconds)
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) -> attributesOfItem(...) -> ftpLogin(taks) -> execute() completionHandler was called
copyItem -> ftpLogin(task) -> ftpDownload(...) -> ftpRetrieve(...) -> attributesOfItem(...) -> ftpLogin(taks) -> execute() ------> error: defer war called
error: Optional(Error Domain=NSURLErrorDomain Code=-1017 "(null)" UserInfo={NSErrorFailingURLStringKey=ftp://<myhost>:21/, NSURL=ftp://<myhost>:21/, NSErrorFailingURLKey=ftp://<myhost>:21/}), where <myhost> ist the correct host name of my server.
copyItem -> ftpLogin(task) -> ftpDownload(...), onTask was called
copyItem -> ftpLogin(task) -> ftpDownload(...), progress Date has been set
(wait for 5 seconds)
copyItem -> ftpLogin(task) -> ftpDownload(...)  completionHandler closure was called with error: NSURLErrorDomain error -1001
```

Do you have any idea what could have happened here? I could try some deeper search, but right now I am lost and missing an idea where to search.

**Comment by amosavian** [comment]
I found out what is happen and fixed it. There is another minor issue to fix and I will push commit after fixing.
Thanks

**Comment by JackPearse** [comment]
You're a magician! That's quick. Thank you very much for the professional diagnosis. It was really fun to browse your code. A really elegant framework! Thank you very much.

**Comment by amosavian** [comment]
Thank you so much. Indeed this framework needs heavy refactoring.

I could not fix the other issue, which caused corrupted file to be uploaded with size less than source file. I will work on it and will inform you when a fix becomes available.

**Comment by amosavian** [comment]
@JackPearse please find latest commit

**Comment by JackPearse** [comment]
Works like a charm!
