### ISSUE TITLE
NSConcreteFileHandle Operation timed out

### ISSUE THREAD

**Issue by charanjit1987** [amosavian/FileProvider#106]
Hi, 

I am facing this crashed after successfully download video from FTP server.

Terminating app due to uncaught exception 'NSFileHandleOperationException', reason: '*** -[NSConcreteFileHandle writeData:]: Operation timed out'

Any help would be appreciated.

**Comment by amosavian** [comment]
I think this is a problem from your disk. This operation should not be timed out.

Eventually I will switch to `NSStream` from `NSFileHandle` soon.

**Comment by amosavian** [comment]
I think this is a problem from your disk. This operation should not be timed out.

Eventually I will switch to NSStream from NSFileHandle soon.

**Comment by charanjit1987** [comment]
Yes,
Problem was from my end. its fixed now. 
Thanks for reply.
