### ISSUE TITLE
Enable To Get Download Progress

### ISSUE THREAD

**Issue by charanjit1987** [amosavian/FileProvider#107]
Hi,

I have another concern, if i download video from FTP using below method

copyItem(path: String, toLocalURL destURL: URL, completionHandler: SimpleCompletionHandler) -> Progress?

it always return 0 for progress. how to get actual downloaded progress.

Any Help.

**Comment by amosavian** [comment]
You mean `progress.fractionCompleted` ?

**Comment by charanjit1987** [comment]
Thanks For quick reply i will try it and update you.
