### ISSUE TITLE
HELP WANTED - Addchild example use

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#110]
I have this method:
```
func upLoadMultiPhotoWithAddChild(folder:String, namePhotos:[String], completion: GeoCompletionHandler) -> Progress {
        progress = Progress(totalUnitCount: Int64(namePhotos.count)*2)
        for namePhoto in namePhotos {
            guard progress?.isCancelled != true else {
                return progress!
            }
            let createProgress = webdav?.create(folder: "test", at: "/", completionHandler: { (error) in
                if let error = error {
                    if self.handleWebdavError(error: error).errorCode != 405 {
                        completion!(self.handleWebdavError(error: error))
                        return
                    }
                }
                let copyProgress = self.webdav?.copyItem(localFile: namePhoto.toLocalURL(), to: namePhoto.toRemotePath(destFolder: "test"), completionHandler: { (error) in
                    if let error = error {
                        completion!(self.handleWebdavError(error: error))
                        return
                    }
                    completion!(GeoErrorStruct())
                })
                // Add the copyProgress task's progress as a child to the overall progress.
                self.progress?.addChild(copyProgress!, withPendingUnitCount: 1)
            })
            // Add the writeProgress task's progress as a child to the overall progress.
            progress?.addChild(createProgress!, withPendingUnitCount: 1)
        }
        return progress!
    }
```
In my View Controller:
```
@IBAction func uploadMultiPhoto(_ sender: UIButton) {
        WebdavHelper.shared.setWebdav()
        progressView.setProgress(0, animated: true)
        let progress = WebdavHelper.shared.upLoadMultiPhotoWithAddChild(folder: "test", namePhotos: namePhotos) { (geoError) in
            if geoError.errorCode == nil {
                print("Upload foto riuscito.")
            }
        }
        progressView.observedProgress = progress
    }
```
Unfortunately, even if the upload of the photos has been properly completed, progressView never reaches 1, that is at the end: why? Where am I wrong?

**Comment by amosavian** [comment]
Sorry I'm late.

Progress for file operations like creating folder, server-side copying, moving and removing are not byte-based. But completed units would either 0 or 1. I think it's not suitable to merge it with a progress which is byte-based, like downloading/uploading.

**Comment by CPiersigilli** [comment]
Very clear. I will change the code according to your explanations. Thank you.

**Comment by amosavian** [comment]
@CPiersigilli If you still have issue with progress, re-open this issue.

**Comment by CPiersigilli** [comment]
I have modified the code that I attached below, but for one time work fine, the second time I have this error: Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT) at line `380`:` let progress = progress ?? Progress(totalUnitCount: 1)` from `open class HTTPFileProvider: NSObject, FileProviderBasicRemote, FileProviderOperations, FileProviderReadWrite, FileProviderReadWriteProgressive {`
```
import UIKit
class ViewController: UIViewController {
    var namePhotos = [String]() //Array of 4 photo to test
    var progressArray = [Progress?]() //To cancel upload from "cancelUpload("
    
    @IBAction func cancelUpload(_ sender: UIButton) {
        for progress in progressArray {
            progress?.cancel()
        }
    }

    @IBAction func uploadMultiPhotoWithProgressPie(_ sender: UIButton) {
        //Set webdav variable.
       WebdavHelper.shared.setWebdav()
        let group = DispatchGroup()
        
        var geoErrorArray = [GeoErrorStruct]()
        var progressLocal = Progress()
        
      // I need to remove all the elements of progressArray, otherwise they increase
      //and I can not verify if the processes have been deleted or not, but it does not work
        progressArray.removeAll()
        
        for (index,namePhoto) in namePhotos.enumerated() {
            group.enter()
            progressLocal = WebdavHelper.shared.upLoadPhotoWithAddChild(folder: "test2", namePhoto: namePhoto) { (geoError) in
                if (self.progressArray[index]?.isCancelled)! {
                    group.leave()
                    return
                }
                geoErrorArray.append(geoError)
                if !geoError.isOk {
                    group.leave()
                    return
                }
                group.leave()
            }
            progressArray.append(progressLocal) //Increment number of progressArray element
            group.notify(queue: .main) {
                //Single photo upload check
            }
        }        
        group.notify(queue: .main) {
            print("all activities complete 👍")
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Set namePhotos array to test code
        namePhotos = ["Milano.jpg","Firenze.jpg","Singapore.jpg","Melbourne.jpg"]
    }
}
```
Where am I doing wrong? If I do not insert: "progressArray.removeAll ()" everything works fine, but I can not control the deletion of processes because progressArray increases the number of elements.
Thanks for the help you can give me.

**Comment by CPiersigilli** [comment]
I have performed other tests. The error in my code is not what I thought. Definitely wrong to run the `progress?.cancel` from `cancelUpload(`.
What is the correct way to cancel a file upload?

**Comment by CPiersigilli** [comment]
The error could also be in WebdavHelper:
```
import Foundation
import UIKit

typealias GeoCompletionHandler = ((_ geoError: GeoErrorStruct) -> Void)?

final class WebdavHelper {
    static let shared = WebdavHelper()
    private init() { }
    
    var webdav: WebDAVFileProvider?
   
    // Funzione che inizializza la variabile webdav per la gestione degli upload e download dei media
    func setWebdav () {
        let webdavPath = "https://webdav.pcloud.com"
        let username = "xxx@yyyyy"
        let password = "zzzzzz"
        
        let webdavURL = URL(string: webdavPath)
        let credential = URLCredential(user: username, password: password, persistence: .forSession)
        
        webdav = WebDAVFileProvider(baseURL: webdavURL!, credential: credential)
    }
    
    func upLoadPhotoWithAddChild(folder:String, namePhoto:String, completion: GeoCompletionHandler) -> Progress {
        var copyProgress:Progress?
   
       //AvdLee/MutableProgress.swift from github.com
       //I need this statement, otherwise copyProgress return always nil.
        let localProgress = MutableProgress()
        
        _ = webdav?.create(folder: folder, at: "/", completionHandler: { (error) in
            let geoError = self.handleWebdavError(isFolder: true, error: error)
            if !geoError.isOk {
                completion!(geoError)
                return
            }
            copyProgress = self.webdav?.copyItem(localFile: namePhoto.toLocalURL(), to: namePhoto.toRemotePath(destFolder: folder), completionHandler: { (error) in
                let geoError = self.handleWebdavError(isFolder: false, error: error)
                if !geoError.isOk {
                    completion!(geoError)
                    return
                }
                completion!(GeoErrorStruct())
            })
            localProgress.addChild(copyProgress!)
        })
        return localProgress
    }
    
    func handleWebdavError(isFolder:Bool, error:Error?) -> GeoErrorStruct {
        var geoError = GeoErrorStruct() //isOk = true, errorCode = nil, errorDescription = nil
        if let error = error as? URLError {
            switch error.code {
            //Manage URLError
            }
        }
        if let error = error as? FileProviderHTTPError {
            switch error.code {
            //Manage FileProviderHTTPError
            }
        }
        return geoError //isOk = true, errorCode = nil, errorDescription = nil
    }
} 
```
Can you help me?

**Comment by amosavian** [comment]
Please try last commit @CPiersigilli

**Comment by CPiersigilli** [comment]
I tested my code with the latest version (Fix #109, refactoring) of your `filesprovider`, getting the same error if I add the line `progressArray.removeAll()` to `@IBAction func uploadMultiPhotoWithProgressPie(` in `ViewController`.
In particular I can not block the upload with the function:
```
@IBAction func cancelUpload(_ sender: UIButton) {
        for progress in progressArray {
            progress?.cancel()
        }
    }
```
and if I remove from `func upLoadPhotoWithAddChild(` in `WebdavHelper.swift` the line `let localProgress = MutableProgress()`, `localProgress` return always `nil`.
Can you help me?

**Comment by amosavian** [comment]
Pardon me I forgot to push. Please try again @CPiersigilli

**Comment by CPiersigilli** [comment]
I tested my code with the latest version (Fix remote session crash, minor fixes) of your `filesprovider`, getting the same error if I add the line `progressArray.removeAll()` to `@IBAction func uploadMultiPhotoWithProgressPie(` in `ViewController`.
In particular I can not block the upload with the function:
```
@IBAction func cancelUpload(_ sender: UIButton) {
        for progress in progressArray {
            progress?.cancel()
        }
    }
```
and if I remove from `func upLoadPhotoWithAddChild(` in `WebdavHelper.swift` the line `let localProgress = MutableProgress()`, `localProgress` return always nil and crash the code.

**Comment by CPiersigilli** [comment]
Are you sure there is something wrong with my code?
Is it correct to use `progressArray.removeAll()` to reset `progressArray` array or is there another way to do it?
Why `progress?.cancel()` does not block the upload?
I thank you in advance for the answers you will give me.

**Comment by amosavian** [comment]
I'm not sure. I never worked with MutableProgress. The progress from uploading is nil?

**Comment by CPiersigilli** [comment]
If I remove the line `let localProgress = MutableProgress()` from `WebdavHelper` (see above) `copyProgress` return always nil, otherwise it works very well, but I have to add, too, `localProgress.addChild(copyProgress!)`.
I tried, too, with `let localProgress = Progress ()` and `localProgress.addChild(copyProgress!, withPendingUnitCount: 1)`, but don't work.
Is it possible that using `MutableProgress` (click [here](https://gist.github.com/AvdLee/6c7353fab031f11f6c9e47594ee9cfa8)), `progress?.cancel ()` does not work?
How can I do, considering that I need to create the folder first, with your `_ = webdav?.create(folder:`, and then upload the file with your `copyProgress = self.webdav?.copyItem(localFile:` (see `func upLoadPhotoWithAddChild(folder` in `WebdavHelper` above)?
I can not understand if something is wrong in my code or how I use your `filesprovider`, to block the upload of a series of files.
I hope you can help me.
Thank you.

**Comment by amosavian** [comment]
I checked source code and it's impossible to have nil progress returned from `copyItem(localFile:, to:)`. Furthermore how you can add it as a child to MutableProgress if it returns nil?

**Comment by CPiersigilli** [comment]
You are probably right, but if I removed `let localProgress = MutableProgress()` and `localProgress.addChild(copyProgress!)` in` WebdavHelper`, when I call `func upLoadPhotoWithAddChild(` from `@IBAction func uploadMultiPhotoWithProgressPie(` in `ViewController` I have the error shown under:
<img width="789" alt="schermata 2018-07-26 alle 21 31 46" src="https://user-images.githubusercontent.com/17962752/43284213-649929e2-911b-11e8-824b-930dece32b0a.png">
Instead adding `let localProgress = MutableProgress()` and `localProgress.addChild(copyProgress!)` in` WebdavHelper` work fine, but I can not block the upload (see video below, excuse me if it is too big).
![fileproviderexample](https://user-images.githubusercontent.com/17962752/43285142-545bc19a-911e-11e8-9192-4b8609fc00d0.gif)
I do not know how to change the code to block the upload of all files with `progress.cancel()`.

**Comment by CPiersigilli** [comment]
If I change `let localProgress = MutableProgress()` and `localProgress.addChild(copyProgress!) `in `WebdavHelper` with `let localProgress = Progress()` and `localProgress.addChild(copyProgress!, withPendingUnitCount: 1)` work, but it does not update the progressPieView.
I do not attach the gif, because too intrusive.
I have no more ideas to change the code and make it work.

**Comment by amosavian** [comment]
You must use DispatchGroup or something like that if you want to convert an async operation to sync one. You are trying to return copy progress while the close inside `create(folder:)` is not executed yet!

**Comment by amosavian** [comment]
That localPorgress approach also should work, but I don't know that `MutableProgress` is guaranteed to work or not. That class is possibly not compatible with `UIProgressView`

**Comment by CPiersigilli** [comment]
You are right. After other tests, I discovered that the problem is using `copyItem(localFile:` inside `create(folder:`, but I do not know how to modify the code to make it work. I tried with this function, it works, but it is very slow.
```
func upLoadPhotoWithAddChildWithDispatchGroup(folder:String, namePhoto:String, completion: GeoCompletionHandler) -> Progress {
        let group = DispatchGroup()        
        group.enter()
        _ = webdav?.create(folder: folder, at: "/", completionHandler: { (error) in
            let geoError = self.handleWebdavError(isFolder: true, error: error)
            if !geoError.isOk {
                group.leave()
                return
            }
            group.leave()
        })
        group.wait()
        let copyProgress = self.webdav?.copyItem(localFile: namePhoto.toLocalURL(), to: namePhoto.toRemotePath(destFolder: folder), completionHandler: { (error) in
            let geoError = self.handleWebdavError(isFolder: false, error: error)
            if !geoError.isOk {
                completion!(geoError)
                return
            }
            completion!(GeoErrorStruct())
        })
        return copyProgress!
    }
```
Do you have any idea how to change the code to make it fast, for:
- create a folder with `.create(folder:`, if not existing;
- upload the file with `.copyItem(localFile:`.
Thank you.

**Comment by CPiersigilli** [comment]
After other test and study, I found a resolution with `@escaping`:

```
func upLoadPhoto(folder:String, namePhoto:String, completion: @escaping (GeoErrorStruct) -> Void, returnProgress: @escaping (Progress?) -> Void) {
        _ = webdav?.create(folder: folder, at: "/", completionHandler: { (error) in
            let geoError = self.handleWebdavError(isFolder: true, error: error)
            if !geoError.isOk {
                completion(geoError)
                return
            }
            let copyProgress = self.webdav?.copyItem(localFile: namePhoto.toLocalURL(), to: namePhoto.toRemotePath(destFolder: folder), completionHandler: { (error) in
                let geoError = self.handleWebdavError(isFolder: false, error: error)
                if !geoError.isOk {
                    completion(geoError)
                    return
                }
                completion(GeoErrorStruct())
            })
            returnProgress(copyProgress)
        })
    }
```
