### ISSUE TITLE
Crash when I use 76aee40 of 05/08/18 instead 38fb3fc of 26/07/18

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#112]
Under the video with the use of your `FileProvider` version 38fb3fc of `07/26/2018`:
![video_success](https://user-images.githubusercontent.com/17962752/44199689-0eec9080-a145-11e8-8dcc-31eaa3a06d78.gif)

Under the video with the of `FileProvider` version 76aee40 of `05/08/18`:
![video_error](https://user-images.githubusercontent.com/17962752/44200554-2af13180-a147-11e8-866c-0e04283e38c5.gif)
The error, in your `SessionDelegate.swift`  is:
<img width="694" alt="schermata 2018-08-16 alle 11 27 30" src="https://user-images.githubusercontent.com/17962752/44200671-71469080-a147-11e8-9171-93bcf565bd47.png">
My function, which calls your FileProvider, used for the two videos is:
```
func upLoadPhoto(index:Int, folder:String, namePhoto:String, progressPie:ProgressPieView, completion: GeoCompletionHandler) {
        progressPie.setProgress(0.0, animated: true)
        let localFileURL = namePhoto.toLocalURL()
        let to = namePhoto.toRemotePath(destFolder: folder)        
        let createProgress = webdav?.create(folder: folder, at: "/", completionHandler: { (error) in
            let geoError = self.handleWebdavError(isFolder: true, index:index, error: error)
            if !geoError.isOk {
                completion!(geoError)
                return
            }
            let copyProgress = self.webdav?.copyItem(localFile: localFileURL, to: to, completionHandler: { (error) in
                let geoError = self.handleWebdavError(isFolder: false, index: index, error: error)
                if !geoError.isOk {
                    completion!(geoError)
                    return
                }
                completion!(GeoErrorStruct(index: index)) //isOk = true, errorCode = nil, errorDescription = nil
            })
            self.copyProgressArray.append(copyProgress!)
            progressPie.observedProgress = copyProgress
        })
        self.createProgressArray.append(createProgress!)
    }
```
Can you help me?

**Comment by CPiersigilli** [comment]
I tried to use the `b597244` version. Unfortunately I have no errors, but progress remains always at 0.

**Comment by amosavian** [comment]
@CPiersigilli I'm really sorry. I've a research project which deadline is near and I've llittle time to investigate issues. I will fix it though. Thanks.

**Comment by CPiersigilli** [comment]
@amosavian Do not worry. I will be waiting for your solution to the problem. In the field, for my tests, I will use the `38fb3fc` version of `07/26/2018`.
Thank you.

**Comment by CPiersigilli** [comment]
Do you have any news for this problem?
