### ISSUE TITLE
HELP WANTED - How to rename a folder contained in a webdav server

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#120]
Which function or set of function should I use to change the name of a folder contained in a webdav server?
I tried in different ways, without succeeding.
Thank you.

**Comment by Destripador** [comment]
` provider.moveItem(path: file.path, to: "\(self.current?.path ?? "")/\(AddHereYourNewNameVariable)", overwrite: false, completionHandler: nil)`

this works for me.

[https://www.youtube.com/watch?v=6qwa_lHHLyE&feature=youtu.be](url)

**Comment by CPiersigilli** [comment]
This works for me too. Thank you.
You can publish your example, which is very interesting.
PS: Please change the link of your video to [this](https://www.youtube.com/watch?v=6qwa_lHHLyE&feature=youtu.be).
