### ISSUE TITLE
`attributesOfItem` method  doesn't work for  CloudFileProvider   

### ISSUE THREAD

**Issue by kaich** [amosavian/FileProvider#128]
I have same code for webdav. It works fine. But when I use code as below for icloud. `attributes`  is always `nil` . 

The `path' is refer to a file.

```
provider?.attributesOfItem(path: path, completionHandler: {
            attributes, error in
       
})
```
Does anyone has this problem ?

I have find the reason of the bug. The predicate is wrong. 

` kMDItemPath BEGINSWITH[cd] "/private/var/mobile/Library/Mobile Documents/iCloud~xxxx~xxxxx~com/Documents/Test.kdbx" AND kMDItemPath LIKE[cd] "Test.kdbx"`

**Comment by drallgood** [comment]
I have that same issue. I was trying to check if a directory exists.. but it's always nil

**Comment by drallgood** [comment]
Slight update...  I at least figured out how to get it to work for files. 
Directories still aren't working because of a "/" at the end. 
The logic there is all kinds of wonky
