### ISSUE TITLE
v0.25.1 fails to build in Xcode 10.2 Beta 1

### ISSUE THREAD

**Issue by Westacular** [amosavian/FileProvider#143]
The latest release version of the pod fails to build in Xcode 10.2 Beta 1 — the updates Swift compiler forces full Swift 4.2 mode, and gives an error because of FileObject's `hashValue` override.

The change in https://github.com/amosavian/FileProvider/commit/36c600ebb0d5194c4e5b4c9fd1ad0718cc6e5007 is enough fix that. Should probably publish a new release?

**Comment by esemusa** [comment]
+1 same problem

**Comment by amosavian** [comment]
Update to 0.26.0
