### ISSUE TITLE
Error after installation via Pods

### ISSUE THREAD

**Issue by Dirk23** [amosavian/FileProvider#144]
Hi,

i wanted to add FileProvider to my App and installed it via Pods. After Building my App i get this Error:

```
SMBErrorType.swift:158: error: ERROR:
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

I don't know how to fix that and would be happy to have some help here. Thank you!

Dirk

**Comment by amosavian** [comment]
Problem is solved?

**Comment by Dirk23** [comment]
Yes, must have been some cache problem or so. Thnx
