### ISSUE TITLE
No Progress / totalBytes / bytesSoFar is always 0

### ISSUE THREAD

**Issue by skela** [amosavian/FileProvider#19]
At present the totalBytes / bytesSoFar is always 0. I'm only using the DropboxFileProvider at the moment, but this is most likely going to affect the other providers too.

Uploading files or downloading files, it makes no difference, the totalBytes or bytesSoFar remains at 0 (and progress is NaN) until the download or upload has finished.

**Comment by amosavian** [comment]
Delegates or OperationHandle?

**Comment by skela** [comment]
I'm using the operation handle.

**Comment by amosavian** [comment]
Tnx, I'm a little busy right now I will investigate asap,
Thanks for feedback

**Comment by skela** [comment]
No worries man, thanks for making a fantastic library! :D

**Comment by amosavian** [comment]
Unfortunately I didn't have enough time to add tests. I will do that soon to get errors before publishing version 1.0

**Comment by amosavian** [comment]
@skela please test again to confirm either this bug is solved or not thanks

**Comment by skela** [comment]
I'll pull yer changes and check

**Comment by skela** [comment]
Yup, thats working now :D
