### ISSUE TITLE
Size returned by FileObject always -1, even when it shouldn't be

### ISSUE THREAD

**Issue by skela** [amosavian/FileProvider#20]
Noticed something weird in FileObject.size

	(lldb) po allValues[URLResourceKey.fileSizeKey.rawValue] as? Int64
	nil

	(lldb) po allValues[URLResourceKey.fileSizeKey.rawValue] 
	▿ Optional<Any>
	  - some : 264772

	(lldb) po allValues[URLResourceKey.fileSizeKey.rawValue] as Int
	264772

	(lldb) po allValues[URLResourceKey.fileSizeKey.rawValue] as! Int
	264772

**Comment by amosavian** [comment]
@skela  that fix would break LocalFileProvider. I will fix it by property setter.

**Comment by skela** [comment]
OK sure, then ignore my change, just fix it whatever way you prefer, i can verify in Dropbox-Provider when its done. My change is tested there, so I know that works.

Just out of curiosity, why would it break the LocalFileProvider?

**Comment by skela** [comment]
![screen shot 2016-12-15 at 18 51 45](https://cloud.githubusercontent.com/assets/58268/21221238/92467604-c2f7-11e6-9b75-2f406f1943a0.png)

**Comment by amosavian** [comment]
LocalFileProvider does mapping `URL.resourceValues` result directly into `FileObject.allValues` dictionary. Indeed the the new design of `FileProvider` class is duplicating `URLResourceValues` struct in `Foundation`.
The return value from that API is Int64 I suppose. That's why it worked for me when I using Local provider.

**Comment by skela** [comment]
That doesn't explain it somehow breaking on LocalFileProvider though, does it? Check out my playground code in the screenshot.

**Comment by amosavian** [comment]
I see that your workaround works perfectly, but current setter implementation causes big files' size (>2gb) becomes `-1` in 32bit devices.

**Comment by amosavian** [comment]
I see that your workaround works perfectly, but current setter implementation causes big files' size (>2gb) becomes `-1` in 32bit devices.

**Comment by amosavian** [comment]
I see that your workaround works perfectly, but current setter implementation causes big files' size (>2gb) becomes `-1` in 32bit devices.

**Comment by skela** [comment]
Yeah i never understood why you were doing that in the setter tbh, seemed weird. But in my defence, i did not touch the setter.
