### ISSUE TITLE
WebDAVFileProvider - off-by-one bug in `contents(path:offset:length:completionHandler)`

### ISSUE THREAD

**Issue by SebastianOsinski** [amosavian/FileProvider#24]
Hi! First things first - great library and thank you for it!
I noticed one thing while using WebDAVFileProvider - implementation of `contents(path: String, offset: Int64, length: Int, completionHandler: @escaping ((_ contents: Data?, _ error: Error?) -> Void)) -> OperationHandle?` returns data of length `length + 1`, e.g. for `contents(path: "some-path", offset: 0, length 10, completionHandler: { (data, error) in print(data) }` it returns `data` of length 11. The problem is in `Range` header value which is set as `"bytes=\(offset)-\(offset + length)"` but should be `"bytes=\(offset)-\(offset + length - 1)"`. Also side note, both `offset` and `length` could probably be unsigned types, don't you think?

**Comment by amosavian** [comment]
Weird I didn't noticed yet. Indeed all providers have that issue. Will fix it soon, Thanks.
