### ISSUE TITLE
pointer being freed was not allocated in contents(path:offset:length:completionHandler) in LocalFileProvider 

### ISSUE THREAD

**Issue by SebastianOsinski** [amosavian/FileProvider#25]
Hi I found bug which causes crash in `contents(path:offset:length:completionHandler)` in `LocalFileProvider`. When using this method app crashes with `malloc: *** error for object <address>: pointer being freed was not allocated`. Here is the minimal working example of said bug (just create Single View Application and paste this in app delegate):

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let manager = FileManager.default
        let documents = manager.urls(for: .documentDirectory, in: .userDomainMask).first!
        let filePath = documents.appendingPathComponent("file.bin").path

        let data = Data(bytes: [1, 2, 3, 4, 5, 6])
        manager.createFile(atPath: filePath, contents: data, attributes: nil)

        // INPUT
        let offset: Int64 = 2
        let length = 3
        let aPath = filePath

        let fd_from = open(aPath, O_RDONLY)
        defer { precondition(close(fd_from) >= 0) }

        lseek(fd_from, offset, SEEK_SET)
        var buf = [UInt8](repeating: 0, count: length)
        let nread = read(fd_from, &buf, buf.count)

        let contents = Data(bytesNoCopy: UnsafeMutablePointer<UInt8>(&buf), count: nread, deallocator: .free)

        print(contents)

        return true
    }
```

I investigated it and found out that problem is in `Data(bytesNoCopy: UnsafeMutablePointer<UInt8>(&buf), count: nread, deallocator: .free)` part. You should use copying initializer `Data(bytes:)`. Moreover, instead of using POSIX approach, it would be better and safer to just use `FileHandle`. If you want, I can issue PR fixing that.

**Comment by amosavian** [comment]
Weird because I am using `FileHandle` since few months ago. Which version are you using?

**Comment by SebastianOsinski** [comment]
You're right. For some reason Cocoapods gave me 0.6.3 instead of newest version. I didn't specify version explicitly in my Podfile, so probably it gave me newest version which was available in my local cocoapods specs.

**Comment by amosavian** [comment]
I'm not a Cocoapods guy, but it reports me the current released version is 0.10.3. 🤔

**Comment by SebastianOsinski** [comment]
Yeah, I just needed to run `pod setup` to refresh cocoapods repository (Cocoapods holds a copy of their repository with 'links' to libraries and their versions in your computer and resolves Podfile against this repository). That's a lesson for me - always check if you have newest version of the library before making an issue on Github ;).

**Comment by amosavian** [comment]
pods centralized system is mother of all issues ;)
Glad to see the problem is solved now
