### ISSUE TITLE
Cannot receive error if user's password is incorrect

### ISSUE THREAD

**Issue by didYouUpdateCode** [amosavian/FileProvider#29]
Hello,

This is an awesome library, it save a lot of time to make wheel.
However, we found an issue the callback isn't invoked by contentsOfDirectory of WebDAVProvider if credential is not valid (e.g. user's password is incorrect). 
My code as below, if any misunderstanding, please correct me. Thank you.

```swift
let url = URL(string: "http://192.168.9.103/webdav")!
        
// password is incorrect
let credential = URLCredential(user: "admin", password: "12345", persistence: .none)
        
fileProvider = WebDAVFileProvider(baseURL: url, credential: credential)
        
fileProvider?.contentsOfDirectory(path: path, completionHandler: { (files, error) in
    guard error == nil else {
        print(error!)
        return
    }
            
    for file in files {
        print("URL: \(file.url)")
    }
})
```

**Comment by amosavian** [comment]
Ah, I forgot to check `challenge.previousFailureCount` in `urlSession(_:,didReceive:)` methods, will be fixed soon
