### ISSUE TITLE
Browsing files in Dropbox

### ISSUE THREAD

**Issue by linhcn** [amosavian/FileProvider#35]
I use OAuthSwift to get access tokens from Dropbox. Not sure what would be steps to make it work?

```swift
let _ = oauthswift.authorize(
            withCallbackURL: URL(string: "oauth-swift://oauth-callback/dropbox")!, scope: "", state: "",
            success: { credential, response, parameters in
                
                let dbCredential = URLCredential(user: "MY_API_KEY", password: credential.oauthToken, persistence: .permanent)
                let dbFileProvider = DropboxFileProvider(credential: dbCredential)
                dbFileProvider.delegate = self
        },
            failure: { error in
                print(error.description)
        }
)
```

**Comment by amosavian** [comment]
After success, you should save credential somewhere (e.g. Keychain or `URLCredentialStorage.shared`) and use that to create a provider object.

I'm not sure how you can retain `dbFileProvider` object that is assigned to a local variable. You may need to define a global or instance/class variable to retain `DropboxFileProvider` object

**Comment by linhcn** [comment]
Thanks for your quick support. 

I make it work by moving the FileProvider creation out of `success` block. `dbFileProvider` here is just for testing.

Is it possible to download files to local storage. `copyItem` function doesn't serve my purpose. Or could you point my out how could I browse files on Dropbox and download/get content of a selected file. If it's possible, it would be best for me. 

Thanks

**Comment by linhcn** [comment]
I've just realised that it's a different issue, will open a new issue.

**Comment by amosavian** [comment]
@linhcn there are two methods, `copyItem(localFile:, to:, completionHandler:)` to upload a file and `copyItem(path:, toLocalURL:, completionHandler:)` to download a file. also if you have `Data` instance, you can use `writeContents(path:, contents:, completionHandler:)` and `contents(path:, completionHandler:)` accordingly.

**Comment by linhcn** [comment]
I should have mentioned that the former is what I was using. There was no file downloaded. Again, the following code is not optimal, just for testing:

```
let str = "/ForDownload/abc.pdf"
let fileURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("test").appendingPathComponent("a.txt")
let _ = dbFileProvider.copyItem(path: str, toLocalURL: fileURL) { (error) in
            
}
```

```
func fileproviderSucceed(_ fileProvider: FileProviderOperations, operation: FileOperationType) {
        switch operation {
        case .copy(source: let source, destination: let dest):
            print("\(source) copied to \(dest).")
            
            let fileURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("test")
            let fileBrowser = FileBrowser(initialPath: fileURL)
            self.present(fileBrowser, animated: true, completion: nil)
            fileBrowser.didSelectFile = { (file: FBFile) -> Void in
                print(file.displayName)
            }
        case .remove(path: let path):
            print("\(path) has been deleted.")
            
            
        default:
            print("\(operation.actionDescription) from \(operation.source!) to \(operation.destination) succeed")
        }
    }
```

**Comment by amosavian** [comment]
You should use `fileProviderSucceed` method for informative or UI refresh. no for selecting file. You can call `dbFileProvider.copyItem` method inside `fileBrowser.didSelectFile`completion block.

Furthermore, please catch error in `dbFileProvider.copyItem` completion block and tell me what it says.

**Comment by linhcn** [comment]
I'm not sure I get the idea. The `fileBrowser.didSelectFile` block is to be used after I select a local file. Point is the `dbFileProvider.copyItem(path: str, toLocalURL: fileURL) { (error) in }` is not working. 

My plan is to copy `/ForDownload/abc.pdf` from Dropbox folder, paste it to `documents/test` folder in user device and allow user to browse the files in `test` folder.

I could not capture the `error` as the code inside `dbFileProvider.copyItem` completion block never gets called.

**Comment by amosavian** [comment]
Please update to `0.15.5`

**Comment by linhcn** [comment]
Seems ok now. Thanks @amosavian
