### ISSUE TITLE
FTP Server connection

### ISSUE THREAD

**Issue by karthikvt** [amosavian/FileProvider#40]
I need a help to connect ftp server. When I try to connect it throws error like NSCocoaErrorDomain Code Code=-1017. Is there anything wrong in my code?

`let credentials = URLCredential(user: "demo", password: "password", persistence:URLCredential.Persistence.forSession)
let ftpService = FTPFileProvider(baseURL: URL(string:"ftp://test.rebex.net/")!, credential: credentials, cache: nil)
        if ftpService != nil{
            ftpService?.contentsOfDirectory(path: String(describing: ftpService!.baseURL), rfc3659enabled: true, completionHandler: { (_files:[FileObject], error) in
                if (error != nil){
                    print(error)
                }
            })
        }`

`Optional(Error Domain=NSCocoaErrorDomain Code=-1017 "(null)" UserInfo{NSErrorFailingURLStringKey=ftp://demo:password@test.rebex.net:21/, NSErrorFailingURLKey=ftp://demo:password@test.rebex.net:21/})`

**Comment by karthikvt** [comment]
I got it.

**Comment by amosavian** [comment]
What was the issue 😀

**Comment by karthikvt** [comment]
Actually, It wasn't issue. I just needed a help. I've just used domain name instead of ip address. It worked with ip address.
