### ISSUE TITLE
Question. How to intercept specific error from webdav

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#43]
I have this simple code:
```
operation = webdavFile?.create(folder: nomeCartella.stringValue, at: cartellaDefault!, completionHandler: { error in
                if error == nil {
                    print("The folder was created successfully.")
                }
                else
                {
                    print("The folder was not created for the following error: \(error)")
                }
```
from which I would like to intercept the error codes for specific operations: how can i do it?
For example, I would like to intercept the 401 "Unauthorized / Expired Session" error, indicating that the password or the user is incorrect.
Thanks for the help you can give me.

**Comment by amosavian** [comment]
You m=have to downcast error to FileProviderWebDavError or FileProviderHTTPError e.g.:

```swift
if let error = error as? FileProviderHTTPError {
    switch error.code {
    case .unauthorized:
        // Code to handle 401 error
    default:
        break
    }
}
```

**Comment by CPiersigilli** [comment]
Thank you so much.

**Comment by CPiersigilli** [comment]
Last question for this help wanted/question.
What is the error if a file or folder exists?

**Comment by amosavian** [comment]
I got HTTP status 405 `.methodNotAllowed` from my test server.
