### ISSUE TITLE
How to download a directory through FTP

### ISSUE THREAD

**Issue by fotiDim** [amosavian/FileProvider#45]
I tried using copyItem(path:to) but I am getting The operation couldn’t be completed. `(FileProvider.FileProviderFTPError error 1.)` or `The operation couldn’t be completed. (NSURLErrorDomain error -1101.)`

This is what I try to call:
```
documentsProvider?.copyItem(path: "/MV Basemap Data", to: documentsURL, overwrite: true, completionHandler: { (error) in
            if let error = error { print(error.localizedDescription); return}
        })
```
and the value of documentsURL is
```
"/Users/fotidim/Library/Developer/CoreSimulator/Devices/180E2D19-6BEF-4E5C-B755-523DD587BED7/data/Containers/Data/Application/E0ECFDF7-E8DE-4E14-AFF3-C5D49F9837F8/Documents"
```

**Comment by amosavian** [comment]
You can use `copyItem(path:, toLocalURL:, completionHandler:)` to download file.

Second, it won't handle downloading entire directory. You have to download files one by one. You can use internal functions `recursiveList(path:, useMLST:, completionHandler:)` to get list of all files in a directory btw.

**Comment by fotiDim** [comment]
I tried that already and it works however I don't see any version of `copyItem(path:, toLocalURL:, completionHandler:)` that supports overwriting. Maybe another enhancement to add.

As you said `recursiveList(path:, useMLST:, completionHandler:)` is internal, so this is not convenient. I used `contentsOfDirectory(path:, completionHandler:)` which did the trick.

**Comment by amosavian** [comment]
it's an opensource library and you can fork and enhance according to your need.

You must always provide a unique local url to that function or check for existance before calling function.

**Comment by charanjit1987** [comment]
Hi,
I tried to copy Ftp video file in my local document directory with below method.

copyItem(path:, toLocalURL:, completionHandler:)

its copy the video(.mp4) file to my local directory successfully , but video is not playing.
Any help would be appreciate.
