### ISSUE TITLE
Occasional error when loggin in

### ISSUE THREAD

**Issue by fotiDim** [amosavian/FileProvider#47]
When executing `contentsOfDirectory` on my FTP server I get occasional failures with error code `-1` and errorDescription `220 Welcome to IC Co. FTP Site`. This seems like an instability as it happens totally randomly and quite frequently. Is there anything I can try?

**Comment by amosavian** [comment]
@fotiDim please check either this new commit fix the problem or not

**Comment by fotiDim** [comment]
@amosavian no, I still have the same issue.

**Comment by amosavian** [comment]
would you mind recheck waht is error code and description now?

**Comment by fotiDim** [comment]
@amosavian it's exactly the same

**Comment by amosavian** [comment]
Impossible. I didn't update cocoapods. please install via `git clone`

**Comment by fotiDim** [comment]
I am using your new code. I used `github "amosavian/FileProvider" "master"` in my pod file and I also checked your commit id. The code execution visits the new line you added.

The old error still keeps popping up. Sometimes I get `Error 425: Can't open data connection` but I think this is unrelated.

**Comment by amosavian** [comment]
@fotiDim As I said don't use pod, remove that entry from podfile, then get this library directly via `git clone https://github.com/amosavian/FileProvider` and dragging `FileProvider.xcodeproj` to your project to get latest version. I can't publish an unconfirmed version to pod.

**Comment by fotiDim** [comment]
@amosavian same problem occurred again.

**Comment by amosavian** [comment]
@fotiDim please check if you experience this error with latest commit.

**Comment by amosavian** [comment]
Closed due to inactivity. I believe it has been address as my tests are passing. You can open it if the problem still exists.
