### ISSUE TITLE
Help wanted. Function to check webdav credentials.

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#48]
Could you tell me which function is preferable to use to check webdav credentials? I use, for example: `webdavFile?.contents(path:`. What do you think? I would like to add to the Preferences window.
Thank you.

**Comment by amosavian** [comment]
You don't need to check it anywhere until it's necessary, Don't check it in Preferences pane. Ask user for credential again if provided one is invalid. User may change its credenial anytime and your application should be able to handle this situation

**Comment by CPiersigilli** [comment]
Great idea. I will do as you suggested. Thank you for your answer.
