### ISSUE TITLE
Files with colons do not appear in contentsOfDirectory results in WebDAVFileProvider

### ISSUE THREAD

**Issue by sbporter** [amosavian/FileProvider#49]
When listing a directory using WebDAVFileProvider, I can see files with a colon (i.e. test:test.txt) in the results, but I can't view their name or path.  Other properties of the FileObject are accessible, including size, but the name or path are inaccessible.  Colons in filenames are quite common, especially in unix timestamped log files.

**Comment by amosavian** [comment]
@sbporter If you find any other character which causes `URL(string: ,relativeTo:)` to fail, inform me here.
