### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by LinhTN-AltPlus** [amosavian/FileProvider#54]
I tried to login to my FTP server and get this error:

"220-You are user number 1 of 50 allowed.\r\n220-Local time is now 09:40. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220 You will be disconnected after 15 minutes of inactivity.\r\n331 User ****** OK. Password required"

Please help!

**Comment by tranngoclinh88** [comment]
@amosavian 
Still can not login. The same message above.
The return code is **220**, not **331**

**Comment by amosavian** [comment]
@tranngoclinh88 you had the same problem as @LinhTN-AltPlus ?

**Comment by LinhTN-AltPlus** [comment]
@amosavian It's another account of me. :)

**Comment by amosavian** [comment]
Would you mind provide me a demo account to server?

**Comment by LinhTN-AltPlus** [comment]
@amosavian I've send email for you. Please check. Thanks!

**Comment by amosavian** [comment]
I can't reproduce any problem with your server. it successfully logged in.

**Comment by tranngoclinh88** [comment]
@amosavian I've sent you another account that error occur. Maybe I do somethings wrong.
Can you commit your example. Many thank!

**Comment by tranngoclinh88** [comment]
@amosavian 
When remove useAppleImplementation = false. I logged in success. Thank you very much!

**Comment by amosavian** [comment]
@LinhTN-AltPlus is this issue resolved?

**Comment by amosavian** [comment]
This problem should be solved as I no longer use apple's implementation for FTP.
