### ISSUE TITLE
OneDriveFileProvider has outdate OneDrive API support

### ISSUE THREAD

**Issue by evilutioner** [amosavian/FileProvider#55]
OneDriveFileProvider currently doesn't work. The default API entry base url https://api.onedrive.com/ response error "bad request". OneDriveHelper.swift has issues with url parsing. New OneDrive API operates with 'root:' instead of 'root'

**Comment by amosavian** [comment]
Please check latest commit @evilutioner

**Comment by evilutioner** [comment]
It doesn't work, this api cannot load root folder at least. I discovered additional issues:
1) multiple percent encoding for path folder with spaces changed this " " to %25%25%25%20. Percent encoding operation should be only once per path string. 
2) IOS API - URL(string: rpath, relativeTo: driveURL) returns nil with base url if it contains symbol ":" in path (in onedrive case "root:")

**Comment by evilutioner** [comment]
https://github.com/amosavian/FileProvider/pull/57

**Comment by amosavian** [comment]
Fixed by pull request #57
