### ISSUE TITLE
WebDAVFileProvider.create(folder... not calling delegate 

### ISSUE THREAD

**Issue by pernozzoli** [amosavian/FileProvider#6]
Hi,

noted that  WebDAVFileProvider.create(folder folderName: String, at atPath: String, completionHandler: SimpleCompletionHandler) does not call the delegate.

pls. consider the following change (basically removing the return statement and the completionHandler call as well as building the right response error). Does this reflect your original intention?

Sorry for the formatting.

public func createExtended(folder folderName: String, at atPath: String, completionHandler: SimpleCompletionHandler) {
        let url = absoluteURL((atPath as NSString).appendingPathComponent(folderName) + "/")
        var request = URLRequest(url: url)
        request.httpMethod = "MKCOL"
        let task = self.session.dataTask(with: request, completionHandler: { (data, response, error) in
            var responseError: FileProviderWebDavError?
            if let code = (response as? HTTPURLResponse)?.statusCode , code >= 300, let rCode = FileProviderHTTPErrorCode(rawValue: code) {
                responseError = FileProviderWebDavError(code: rCode, url: url)
            }
            if let response = response as? HTTPURLResponse, let code = FileProviderHTTPErrorCode(rawValue: response.statusCode) , code != .ok {
                responseError = FileProviderWebDavError(code: code, url: url)
            }
            completionHandler?(responseError ?? error)
            self.delegateNotify(.create(path: (atPath as NSString).appendingPathComponent(folderName) + "/"), error: responseError ?? error)
        })
        task.resume()
    }

Cheers
Arno

**Comment by amosavian** [comment]
Hey @pernozzoli , Sorry I can't understand which delegate you mean the first line of func calls the `FileOperationDelegate.fileProvider(shouldDoOperation:)` delegate method and `self.delegateNotify(.create(path: (atPath as NSString).appendingPathComponent(folderName) + "/"), error: responseError ?? error)` calls the `fileproviderSucceed()` method.

**Comment by amosavian** [comment]
@pernozzoli 
not active for more than 25 day. I will close it. You can still post message here if there is any issue.
