### ISSUE TITLE
FTP upload error

### ISSUE THREAD

**Issue by mavicBreak** [amosavian/FileProvider#63]
Hi,

I am facing into the following problem in my macOS application with uploading a file to FTP. Uploading a relatively small file like few hundred kilobytes works like a charm. However when I am uploading bigger files like 30-40 megabytes it always crashes with the following error:

Assertion failed: (_writeBufferAlreadyWrittenForNextWrite == 0), function -[__NSCFURLLocalStreamTask _onqueue_processWriteWork:], file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-811.4.18/Session/LocalStreamTask.mm, line 1561.

libsystem_kernel.dylib__pthread_kill:
    0x7fffabde4d38 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x7fffabde4d3d <+5>:  movq   %rcx, %r10
    0x7fffabde4d40 <+8>:  syscall 
   -----> 0x7fffabde4d42 <+10>: jae    0x7fffabde4d4c            ; <+20>   <----- this crashes
    0x7fffabde4d44 <+12>: movq   %rax, %rdi
    0x7fffabde4d47 <+15>: jmp    0x7fffabdddcaf            ; cerror_nocancel
    0x7fffabde4d4c <+20>: retq   
    0x7fffabde4d4d <+21>: nop    
    0x7fffabde4d4e <+22>: nop    
    0x7fffabde4d4f <+23>: nop  

**My code is:**

`let credential = URLCredential(user: "12345", password: "12345", persistence: .none)
        
let cache = URLCache()`

       let ftpProvider = FTPFileProvider(baseURL: URL(string: "ftp://server")!, passive: true, credential: credential, cache: cache)

        let dir: URL = FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask).last! as URL
        let binURL = dir.appendingPathComponent("/testfile.bin")

        ftpProvider?.copyItem(localFile: binURL, to: "/testfile.bin", completionHandler: { error in

            if error == nil {
                print("ready")
            } else {
                print("\(String(describing: error))")
            }
        })`

I tested on different FTP servers with different files, Xcode 8, swift 3.
I added FilesProvider to my project by drag and drop FilesProvider.xcodeproj into my project and setting the required binaries and framework if it matters (I am new to Xcode).

**Comment by amosavian** [comment]
Which version are you using?

**Comment by mavicBreak** [comment]
The one which was the latest 12 days ago, I downloaded from your repo.

**Comment by amosavian** [comment]
This is a bug in Foundation layer at NSURLSessionStreamTask. I did encounter that when tried to upload several chunk by same session. This issue doesn’t exist in CFStream. I tried to workaround it by creating separate session for each chunk and use ftp `REST` command for multi-part uploading. I didn’t have problem with uploading a 11MB file. I suppose you can resolve this issue by decreasing chunk size for files bugger than 32MB which is defined in [these lines as 512KB.](https://github.com/amosavian/FileProvider/blob/master/Sources/FTPHelper.swift#L663-L669)

Tell me if that resloves your issue

**Comment by amosavian** [comment]
I've switched to my implementation of URLSessionStreamTask rather than Apple's. This bug should be resolved in [this commit](https://github.com/amosavian/FileProvider/commit/d29826c56cb3103efc0f023bbf0a8ea5e11e8344). If you still experience it, please reopen the issue.
