### ISSUE TITLE
Use FileProvider, does the file need to be managed manually synchronously?

### ISSUE THREAD

**Issue by DivenLee** [amosavian/FileProvider#64]
I want to use FileProvider on OSX, and I don't know much about its support for icloud. If I use FileProvider, do I need to manually sync, create, delete, modify, or move files in the sandbox? Or did FileProvider help me do these things automatically?
Also, if icloud has a file update, do I need to manually sync to the local or do FileProvider help me?
Thank you for everything!

**Comment by amosavian** [comment]
I don’t understand what’s the question exactly, but you should enable capability in project settings, then add some codes in `Info.plist` as described [here](https://medium.com/ios-os-x-development/icloud-drive-documents-1a46b5706fe1).
The class will do all the magic necessary to sync and coordinate itself.

**Comment by DivenLee** [comment]
For example, a file is deleted from the A device, and then the B device will delete the file. But I don't know how to notify the B device that a file has been deleted, and then the B device, the files in your sandbox, will also be deleted.
This is where I don't understand.

**Comment by amosavian** [comment]
You can use `registerNotifcation(path:, eventHandler:)` method to register an event handler which will be called when any change occurs. Refresh your file list in handler method.

**Comment by amosavian** [comment]
This repo considers iCloud as a file storage which is more suitable for file manager. If you want to manage documents, I suggest using `NSDocument/UIDocument` or [this repo](https://github.com/iRareMedia/iCloudDocumentSync).

**Comment by DivenLee** [comment]
I still like FileProvider, she makes me feel comfortable. And I've got some inspiration from your cue, I've got a rough idea.
Also, I'd like to know about the registerNotifcation event, including deleting the file? For example, my A device has removed text.txt, and will the B device receive the message?
If the A device or B device does not have a network, does it cause notifications after networking?

Thank you for everything

**Comment by amosavian** [comment]
Theorically it should be triggered by any event including deleting, though there is a small delay (It takes 5 sec to be called in same device that deletes file!). Remember to call `unregisterNotification` method after you’ve done with it.

Example code:
```swift
self.provider.registerNotification(path: “”) { [weak self] in
    self?.tableView.reloadData()
}
```
