### ISSUE TITLE
WebDAVFileProvider doesn't handle deletion results properly.

### ISSUE THREAD

**Issue by RndmTsk** [amosavian/FileProvider#7]
When calling `removeItem(path:completionHandler) -> OperationHandle?` inside `WebDAVFileProvider: FileProviderOperations` the result will be `204` (No Content) which is valid (the item was deleted), however, the completion handler is called with an error whenever the response isn't `207` (Multi-Status).

**Comment by amosavian** [comment]
Thank you for report, I also noticed error report for other methods are not as expected, I will rectify it asap.

**Comment by amosavian** [comment]
https://github.com/amosavian/FileProvider/commit/66fc1e128483081a2b5d8563d161ae6096ab0e5d

**Comment by amosavian** [comment]
Fixed https://github.com/amosavian/FileProvider/commit/66fc1e128483081a2b5d8563d161ae6096ab0e5d
