### ISSUE TITLE
URL parsing failed if contains spaces.

### ISSUE THREAD

**Issue by sinarionn** [amosavian/FileProvider#72]
Problematic code: [https://pastebin.com/naJxdAqY](https://pastebin.com/naJxdAqY)
hrefAbsolute will be nil if hrefString contains unencoded characters (such as space for example)
Possible (fast) solution:  [https://pastebin.com/WNBnYGgh](https://pastebin.com/WNBnYGgh)

**Comment by amosavian** [comment]
This a expected behavior. You must file a bug for your server in first place. Your proposed solution will encode an already percent-encoded string which will create a corrupted string.

**Comment by sinarionn** [comment]
You mean server side should do this percent encoding or you mean it was done on a client side somewhere before this code?

**Comment by sinarionn** [comment]
Maybe this will works? https://pastebin.com/Y8JWSHRt
Unfortunately i can't  do anything with server side because it's a [flashair](http://www.toshiba-memory.com/cms/ru/produktsiya/karty_pamiaty_formata_Wireless_dlia_besprovodnoi_peredatchi_dannykh/FlashAir/index.html)
