### ISSUE TITLE
Swift Package - 

### ISSUE THREAD

**Issue by dhushon** [amosavian/FileProvider#74]
trying to include FileProvider in SPM 4.0.0, generates errors in swift package generate-xcodeproj:

$ swift package generate-xcodeproj
error: package has unsupported layout; found loose source files: /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/CloudFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/DropboxFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/DropboxHelper.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/ExtendedLocalFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/FPSStreamTask.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/FTPFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/FTPHelper.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/FileObject.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/FileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/HTTPFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/LocalFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/LocalHelper.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/OneDriveFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/OneDriveHelper.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/RemoteSession.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/SMBClient.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/SMBFileProvider.swift, /Users/dhushon/work/TensorBoxify/.build/checkouts/FileProvider.git-6221985536385019491/Sources/WebDAVFileProvider.swift

Directory structure inconsistency as we can see here... missing /Sources and /Tests:
DHushon:~/work/TensorBoxify/.build/checkouts$ ls swifter.git--8814129713726061435/
./               .git/            .swift-version   LICENSE          README.md        Swifter.podspec
../              .gitignore       .swiftlint.yml   Package.swift    Sources/         XCode/
DHushon:~/work/TensorBoxify/.build/checkouts$ ls FileProvider.git-6221985536385019491/
./                       .swift-version           LICENSE                  Sources/
../                      .travis.yml              Package.swift            fileprovider.png
.git/                    FilesProvider.podspec    Pod/
.gitignore               FilesProvider.xcodeproj/ README.md

UPDATE: SPM is having a problem with the simple renaming... which is to say, if the root directory is changed to "FilesProvider" then the swift build works.  Unfortunately I think that this means we need to restart the project with a new root?

**Comment by amosavian** [comment]
I’m on vacation. I will fix after returning.

**Comment by dhushon** [comment]
The change that does work is.... add a prefix to Package.swift
+0: // swift-tools-version:4.0

This is required by the SPM4.0 build system.
