### ISSUE TITLE
iOS new Files app access to webdav

### ISSUE THREAD

**Issue by ericavijay** [amosavian/FileProvider#78]
Hello Amir,

Thanks for this great project.  Does importing and registering a Webdav automatically create a NSFileProviderService for access form iPhone/iPad's native Files app?  My desire is to just register our corporate webdav as a provider so all our users automatically get access to all the resources using Files.  It does not seem like Apple Configurator allows for such a registration, looks like we have to write an app, just want to make sure it is possible with the libraries you are providing this can be achieved!

Thanks
Vijay

**Comment by amosavian** [comment]
Despite similar names, this framework is not related to Apple's `FileProvider` framework. I couldn't change name after Apple release iOS 11.

Files app (`NSFileProviderExtension`) extension needs many optimization for memory. I can't afford that due to limited time I have.
