### ISSUE TITLE
FTP contents of directory always returns nil.

### ISSUE THREAD

**Issue by Lelx8** [amosavian/FileProvider#84]
However i can upload a file and download with ftp.

**Comment by amosavian** [comment]
My tests are passing for FTP on my own server (ProFTPD). Please give me a demo ftp account to allow me to check.

**Comment by Lelx8** [comment]
Host: ftp.anamariagraphics.com
Username: carla@anamariagraphics.com
Password: Carla12@#

**Comment by amosavian** [comment]
I've removed credentials

**Comment by amosavian** [comment]
I have no problem on getting lists and contents on my app.

![5ae757c2-4f95-4a18-b1a6-ee54b6b6811e](https://user-images.githubusercontent.com/6725192/36433082-f538c014-1670-11e8-8c65-586311df6ae8.png)

**Comment by Lelx8** [comment]
Can i have the code so i can figure out what i'm doing wrong? Thank you for your time.

**Comment by amosavian** [comment]
My code is not clean and unfortunately, No. But this one may help you:
https://github.com/amosavian/FileProvider/issues/32#issuecomment-291636606

**Comment by Lelx8** [comment]
It's working on the server that i gave. I forgot to specify protocol before url ("ftp://"). Thanks for help.

**Comment by amosavian** [comment]
This is a bug that provider fails to manage url's without scheme
