### ISSUE TITLE
Copy from WebDav to local storage

### ISSUE THREAD

**Issue by benbox69** [amosavian/FileProvider#85]
Good day,

I am a little bit new to Swift and I am not able to use FileProvider correctly.
I am trying to copy a file from a WebDav server to my local folder.

```
let credential = URLCredential(user: "username", password: "password", persistence: .permanent)
       
let webdavProvider = WebDAVFileProvider(baseURL: URL(string: "https://webdav.server.url")!, credential: credential)
        
let fileURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("my document.doc")
        
_ = webdavProvider?.copyItem(path: "/Folders/Dir/my document.doc", toLocalURL: fileURL, completionHandler: nil)
```

I have no error, or no return but the file is not downloaded (I can't see it in Files)...
How to use the functions correctly?
I am not sure how to use the delegate functions, can you explain?

Thanks
Ben

**Comment by amosavian** [comment]
You must retain `webdavProvider` instance, by define it as a global variable or class's instance property. Otherwise WebDAVProvider will invalidates all task upon releasing.
Alternatively you can set `fileProviderCancelTasksOnInvalidating = false`.

Example code:
https://github.com/amosavian/FileProvider/issues/32#issuecomment-291636606

**Comment by benbox69** [comment]
I have corrected my code with the example you gave me... but It's still not working (sorry I am new in iOS development)

``
import UIKit
import FilesProvider

class ViewController: UIViewController, FileProviderDelegate {

    var webdav: WebDAVFileProvider?
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        
        let credential = URLCredential(user: "username", password: "password", persistence: .permanent)
        let webdavServer = URL(string: "https://server-webdav.com")

        webdav = WebDAVFileProvider(baseURL: webdavServer!, credential: credential)!
        webdav?.delegate = self as FileProviderDelegate
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    @IBAction func download(_ sender: Any) {
        
        let localURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("Rev 0.pdf")
        
        var remotePath = "/Folders/OPERATIONS/OPERATIONS MANUALS/Rev 0.pdf"
        remotePath = remotePath.addingPercentEncoding(withAllowedCharacters: .urlFragmentAllowed)!

        _ = webdav?.copyItem(path: remotePath, toLocalURL: localURL, completionHandler: nil)
    }
    
    func fileproviderSucceed(_ fileProvider: FileProviderOperations, operation: FileOperationType) {
        switch operation {
        case .copy(source: let source, destination: let dest):
            print("\(source) copied to \(dest).")
        case .remove(path: let path):
            print("\(path) has been deleted.")
        default:
            print("\(operation.actionDescription) from \(operation.source) to \(String(describing: operation.destination)) succeed")
        }
    }
    
    func fileproviderFailed(_ fileProvider: FileProviderOperations, operation: FileOperationType, error: Error) {
        switch operation {
        case .copy(source: let source, destination: let dest):
            print("copy of \(source) failed.")
        case .remove:
            print("file can't be deleted.")
        default:
            print("\(operation.actionDescription) from \(operation.source) to \(String(describing: operation.destination)) failed")
        }
    }
    
    func fileproviderProgress(_ fileProvider: FileProviderOperations, operation: FileOperationType, progress: Float) {
        switch operation {
        case .copy(source: let source, destination: let dest):
            print("Copy\(source) to \(dest): \(progress * 100) completed.")
        default:
            break
        }
    }
}
``

The errors returned are:

``
Copy /Folders/OPERATIONS/OPERATIONS%20MANUALS/Rev%200.pdf to file:///var/mobile/Containers/Data/Application/D87D0A5F-575F-4D93-9954-A0C5FD2E3A80/Documents/Rev%200: 100.0 completed.
copy of /Folders/OPERATIONS/OPERATIONS%20MANUALS/Rev%200.pdf failed.
/Folders/OPERATIONS/OPERATIONS%20MANUALS/Rev%200.pdf copied to file:///var/mobile/Containers/Data/Application/D87D0A5F-575F-4D93-9954-A0C5FD2E3A80/Documents/Rev%200.
/Folders/OPERATIONS/OPERATIONS%20MANUALS/Rev%200 copied to file:///var/mobile/Containers/Data/Application/D87D0A5F-575F-4D93-9954-A0C5FD2E3A80/Documents/Rev%200.

**Comment by amosavian** [comment]
Please dont do add percent escaping. Leave these nasty implementation details to the library.

**Comment by benbox69** [comment]
It works! Id did that because of a previous failure...
Thanks
