### ISSUE TITLE
WedDavFileProvider. No check error with: isReachable

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#87]
Nel verificare i possibili errori della mia app, ho scoperto che `isReachable` risulta `false`, anche se qualche credenziale (`URL`, `user` and `password`) è errata, senza poterne intercettare l'errore.
Hai qualche idea su come poter utilizzare il tuo `isReachable` o è conveniente utilizzare `Reachability.swift` di Ashley Mills per verificare la connessione?

In checking the possible errors of my app, I've found that `isReachable` is `false`, even if some credentials (`URL`, `user` and `password`) are wrong, without being able to intercept the error.
Do you have any idea how to use your isReachable or is it convenient to use Ashley Mills' `Reachability.swift` to verify your connection?

Thanks in advance.

**Comment by amosavian** [comment]
`isReachable` doesn't check network connectivity. It only checks either server responds successfully to a query or not. Implicitly it does validating credentials.

To check validity of credential, You can use `attributesOfItem()` on root. If it does return `.unauthorized` error, then you can assume credential is not valid.

Usability of `isReachable` is very limited and I strongly against using it as it may introduce race condition bug in your implementation. Simply try to do something and try to act for given error, if there is any.

**Comment by CPiersigilli** [comment]
Ok. To check network connectivity I'll use Ashley Mills' `Reachability.swift`.
To check the credentials `attributesOfItem ()` is faster than `contentsOfDirectory ()`?
To use `attributesOfItem ()` on root, the code below is correct?
```
documentsProvider.attributesOfItem(path: "/", completionHandler: {
    attributes, error in
    if let error = error {
        switch error.code {
        case .unauthorized:
            print("unauthorized")
            return
        default:
            print("Errore webdavFile: \(String(describing: error.errorDescription))")
            return
        }
        print("Credential OK.")
    }
})
```

Other question.
`writeContents (path :, content :, atomically :, completionHandler :)`, create the file if the folder does not exist?
Thank you.

**Comment by amosavian** [comment]
> attributesOfItem () is faster than contentsOfDirectory ()?

It should be faster because it does not enumerate root folder entities.

> Other question.
writeContents (path :, content :, atomically :, completionHandler :), create the file if the folder does not exist?

It's depend on server's behavior. This library doesn't create intermediate directories. Server may create intermediate directories or return an error.

**Comment by amosavian** [comment]
I think I must change `isReachable()` signature to return an error instead of boolean. You are right

**Comment by CPiersigilli** [comment]
Thank you. I wait for the changes.

**Comment by CPiersigilli** [comment]
> Other question.
> writeContents (path :, content :, atomically :, completionHandler :), create the file if the folder does not exist?

_It's depend on server's behavior. This library doesn't create intermediate directories. Server may create intermediate directories or return an error._

Thank you for this very clear clarification.
