### ISSUE TITLE
FTP Upload TLS/SSL Error

### ISSUE THREAD

**Issue by webmasterjunkie** [amosavian/FileProvider#88]
I am getting an error when trying to upload using a file using a FTP handler. Here is the function that I am calling:

```swift
func sendDataToServer(_ file: URL){
        let credentials = URLCredential(user: "sample", password: "sample", persistence: .forSession)
        
        let host = URL(string: "ftp://ftp.site.com")!
        let ftpProvider = FTPFileProvider(baseURL: host, passive: false, credential: credentials)!
        
        ftpProvider.copyItem(localFile: file, to: "/directory/test.csv", overwrite: true, completionHandler: { (error) in
            print(error?.localizedDescription ?? "no error")
        })
    }
```

Once this is executed I get the following error:

`Invalid sequence of commands (AUTH SSL/TLS required prior to authentication).`

Could you advise on what the next steps would be for this?

Thanks in advance!

**Comment by amosavian** [comment]
Change this line to have ftps, or set port to 990:

```swift
let host = URL(string: “ftps://ftp.site.com”) // Implicitly on port 990
// OR
let host = URL(string: “ftp://ftp.site.com:990”)
// OR
let host = URL(string: “ftpes://ftp.site.com”) // Explicit mode
```

**Comment by webmasterjunkie** [comment]
Greatly appreciated! I have changed it to:

```
let host = URL(string: "ftpes://ftp.site.com") // Explicit mode
```

This has made an output change to a different error:

```
331 Password required for *redacted*
```

I have confirmed this password is valid.

**Comment by webmasterjunkie** [comment]
Updated code:

Swift 4
Xcode 9.2

```
func sendDataToServer(_ file: URL){
    let credentials = URLCredential(user: "sample", password: "sample", persistence: .forSession)
    let host = URL(string: "ftpes://ftp.site.com")!
    let ftpProvider = FTPFileProvider(baseURL: host, passive: true, credential: credentials)!
    let desc = "Uploading file in \(ftpProvider.type)"
    
    let progress = ftpProvider.copyItem(localFile: file, to: "/directory/test.csv"){ (error) in
        print("\(desc) failed: \(error?.localizedDescription ?? "no error desc")")
    }
    
    print(progress?.fractionCompleted ?? 0)
}
```

Here is the new output in full:

```
0.0
0.0
Uploading file in FTP failed: 331 Password required for *redacted*.
Uploading file in FTP failed: 331 Password required for *redacted*.
```

**Comment by amosavian** [comment]
If you know swift well, please put a breakpoint on [this line](https://github.com/amosavian/FileProvider/blob/master/Sources/FTPHelper.swift#L51) and check the code behavior.

**Comment by webmasterjunkie** [comment]
That is where we may have a problem, I don't know too much about Swift. I can place a breakpoint though. Here is what I have from the stack trace:

![screen shot 2018-03-09 at 3 54 56 pm](https://user-images.githubusercontent.com/1320031/37216363-7ed8d82e-23b2-11e8-9e36-945a7724a5ab.png)

Same output in the Debug area. Does this help any?

**Comment by amosavian** [comment]
I meant to do trace. Can I have a demo account a server similiar to yours in order to test?

**Comment by amosavian** [comment]
Furthermore please check https://github.com/amosavian/FileProvider/blob/master/Docs/Sample-iOS.swift to see correct sample code.

**Comment by webmasterjunkie** [comment]
Thanks for the support. I have added you to a private repository with the modified code to test an upload to this server. Please let me know if you can see any reason why it won't push the file up.

**Comment by amosavian** [comment]
I shall check when I got free. Thanks

**Comment by amosavian** [comment]
I've used my test cases instead of your app. All bugs has been fixed and I will push a commit soon. The only thing is you must use `.extendedPassive` mode for your server instead of `.passive` mode.

```swift
let provider = FTPFileProvider(baseURL: url, mode: .extendedPassive, credential: cred)!
```

Other issues will be fixed after I push new commit.

**Comment by webmasterjunkie** [comment]
Excellent support sir.

**Comment by amosavian** [comment]
@webmasterjunkie Please check latest commit.

**Comment by webmasterjunkie** [comment]
Confirmed. Thanks.

**Comment by amosavian** [comment]
It still has problems with deleting folder recursively and reading file contents, though I think you don't need them at least now.

**Comment by jbetancourtlopez** [comment]
Hi, I have the follow error: The operation couldn’t be completed. (NSURLErrorDomain error -1101.)

This is my code: 
`@IBAction func upload(_ sender: Any) {
        print("Inicio carga de archivo")
        

        let localURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!.appendingPathComponent("ic_user_profile.jpg")
        let remotePath = "/ic_user_profile11111.jpg"
        
        
        let credential = URLCredential(user: self.username, password: self.password, persistence: .forSession)
        
        let ftpProvider = FTPFileProvider(baseURL: self.server, mode: .extendedPassive, credential: credential)!
        
        let progress = ftpProvider.copyItem(localFile: localURL, to: remotePath ){ (error) in
            print("Failed: \(error?.localizedDescription ?? "Error")")
        }
        
    }`

**Comment by amosavian** [comment]
@jbetancourtlopez The error is `kCFURLErrorFileIsDirectory` which means you are trying to upload a non-regular (directory or pipe) instead a file. Or the file does not exist?
