### ISSUE TITLE
FTP data connection request times out every time on iOS 11 

### ISSUE THREAD

**Issue by brashkov** [amosavian/FileProvider#89]
So the problem is that I'm currently working on a project and when I was testing it on iOS 9, everything was fine , but when we updated the devices to iOS 11, every FTP data connection request times out.

**Comment by amosavian** [comment]
Do you have tested `.extendedPassive` mode? Some sites only work with that mode.

**Comment by brashkov** [comment]
Yes I tried also I tried couple of different ftp servers, the problems comes when I try to access the files. The process is like this:

1. Im getting 331 code and I'm setting the password.
2.After that I'm receiving 230 code.
3. And lastly I'm getting 227.

After that when I want to list the files the request times out and again, Its only happening on iOS 11 if I try to list the files from an FTP server on iOS 9 everything is fine

**Comment by amosavian** [comment]
My tests are passing for my own server. Maybe your server implementation is different from mine. Would you mind giving me a demo account?

**Comment by brashkov** [comment]
Yeah, the servers that I'm currently using for testing are:
-server: ftp.uconn.edu
account: anonymous

-server:speedtest.tele2.net
account: anonymous

And again, your framework is doing perfectly well with iOS 9, but the problem only occurs in iOS 11

**Comment by amosavian** [comment]
Did you disable App Transport Layer (ATS) in your project settings?

**Comment by brashkov** [comment]
Yes, I tried different configurations with the ATS, but the problem is not coming from there

**Comment by amosavian** [comment]
I have no problem with iOS 11, using my library in my own app. `speedtest.tele2.net` was one of my testing servers. I checked uconn with no problem. Please check again your project settings for ATS.

**Comment by brashkov** [comment]
Okay, whole morning I'm playing around with this useAppleImplementation, but nothing changes. I'm setting it to false in the FTPFileProvider init() method. If I'm doing something wrong correct me. Thank you !

**Comment by amosavian** [comment]
Sorry for wrong clue. Please set `FPStreamTask.defaultUseURLSession` to false.

Initially I implemeted `FPStreamTask` as a drop-in replacement for `URLSessionStreamTask` to allow falling back to `CFStream` in iOS 8 in which Apple’s stream task is unavailable and allow to use modern Apple’s implementation in newer OSes.

I finally had to abandon Apple’s `URLSessionStreamTask`as it had critical bugs, including this one and an assertion crash.

**Comment by brashkov** [comment]
Thank you ! Really appreciate the help. It worked now I will run some test for basic operations with the ftp connection and will let you know if there is something else, but this fixed the timing out. Again thanks for the help!

**Comment by amosavian** [comment]
It seems problem has been solved. Please reopen issue if you still have the same problem.

**Comment by rajan2211** [comment]
Where can I set FPStreamTask.defaultUseURLSession = false?

**Comment by amosavian** [comment]
@rajan2211 it is set to false by default

**Comment by rajan2211** [comment]
When I upload on FTP, it does nothing and no delegates are called. After some time time out occur.

**Comment by oniksfly** [comment]
Get the same error on iOS 14: 

```
nw_endpoint_create_bonjour_service invalid empty string name
nw_endpoint_create_bonjour_service invalid empty string name, dumping backtrace...
```
