### ISSUE TITLE
Use s.swift_version in Podspec instead of .swift-version file

### ISSUE THREAD

**Issue by Westacular** [amosavian/FileProvider#90]
Issue:

- FilesProvider fails to build using Swift 3.x (it's depending on the altered semantics of `private` in Swift 4.0)
- CocoaPods 1.4.0 apparently doesn't fully respect `.swift-version` files anymore; the replacement is using `swift_version` in the podspec DSL.
- Under some circumstances, Cocoapods 1.4.0 will select Swift 3.2 as the default Swift version, and apply that to the target build settings for FilesProvider.
- FilesProvider will then fail to build.

Solution:

Add `s.swift_version = '4.0'` to FilesProvider.podspec, and delete `.swift-version`

**Comment by amosavian** [comment]
You can create pull request to become a contributor if you mind. Otherwise tell me I would do it.

**Comment by amosavian** [comment]
Updated and fixed by https://github.com/amosavian/FileProvider/commit/6c34a4e9a8b47e746a29563e039c2479d13b37a8
