### ISSUE TITLE
Upload UIImage to FTP

### ISSUE THREAD

**Issue by reenaphilip** [amosavian/FileProvider#92]
I want to upload a UIImage from camera roll to server folder. How will I use WebDAVFileProvider to implement this ?
I tried using 
webdav?.writeContents(path: remotePath, contents: imageData, atomically: true, completionHandler: nil)
But I am getting error "Modifying on /fileprovider.png failed."

**Comment by reenaphilip** [comment]
Sorry for wrongly put it as FTP server. I am completely blank about this kind of uploading. Usually upload images using multipart form data POST service. But I have server location and need to upload directly to server folder with POST service. Hope I can use this WebDAV for doing the same.
   I have the address of that folder location and credentials. Server   : http://mservice.mbb.com. I have folder inside this  called Business and need to upload image to that. 
   I tried converting an image saved in Assets to Data by using UIImagePNGRepresentation.
And used  webdav?.writeContents(path: remotePath, contents: imageData, completionHandler: nil) to upload to the location. 
In the above API what is the remote path in this situation?

**Comment by amosavian** [comment]
This library strictly implements WebDAV implementation. To upload using POST method or multipart, you can simply use [Alamofire](https://github.com/Alamofire/Alamofire).

Here is documentation [to upload data, file and multipart](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#uploading-data-to-a-server).
