### ISSUE TITLE
Crash after retrieved a file (image)

### ISSUE THREAD

**Issue by gorbat-o** [amosavian/FileProvider#93]
Hey,

Nice library,
But I have a crash when I am trying to get the content of a file in the iCloud,

![image](https://user-images.githubusercontent.com/7542553/39552657-669205d2-4e6a-11e8-9c55-87f69447f709.png)

```
documentsProvider?.contents(path: content.url.relativeString, completionHandler: { data, error in
    print(error)
})
```

Maybe I am using the wrong variable for the path ??? :/
Thanks for future help :)

**Comment by amosavian** [comment]
Please remark all calls to private function `monitorFile()` in problematic methods until I fix the issue.

I didn't retain the object that passed to `context` variable. I have to change architecture of this part entirely.

**Comment by gorbat-o** [comment]
Thank you for this fast answer,
Do you have a workaround ?

**Comment by amosavian** [comment]
The issue should be fixed entirely in latest commit. You must do a `git pull`.

**Comment by gorbat-o** [comment]
I tried a pod update,
I am wondering if you didn't forget to update the version ?

**Comment by amosavian** [comment]
Unfortunately it's almost impossible to have test unit for iCloud provider, thus there is no way to guarantee as I can do for WebDav, Dropbox or FTP.

I didn't release a new version. I usually update pod when the version is stable. It would be nice if you can switch to `git clone` to test. Otherwise I have to release new version as my tests are okay

**Comment by gorbat-o** [comment]
Ok, I tried and it works.
Thank you so much for your reactivity.

**Comment by amosavian** [comment]
Thanks. I will release a new pod version in minutes to allow you to switch back.

**Comment by gorbat-o** [comment]
weird, it didn't update my pod :/

**Comment by amosavian** [comment]
I'm writing release note and waiting to Travis checks to be passed. You can check within an hour.
