### ISSUE TITLE
HELP WANTED - Access denied to webdav servers

### ISSUE THREAD

**Issue by CPiersigilli** [amosavian/FileProvider#96]
I have carried out tests using your `FileProvider` with `pcloud.com` and `box.com`, as I have always done with success in these months, discovering that access via webdav is no longer allowed, but only through authentication.
How can I solve the problem?
Will I have to use authentication?
Can you give me a little example?
Are there any webdav servers that you can still access through your `FileProvider`?
Thank you.

**Comment by amosavian** [comment]
My test case is using Box and it's being passed.

**Comment by CPiersigilli** [comment]
I'm sorry. You're right. I was wrong to use your FilesProvider with the latest version.
Using your `Sample-iOS.swift` to perform tests I realized that with the functions `webdav? .writeContents (path :`, `webdav? .copyItem (path:` and `webdav? .copyItem (localFile:` I get two notifications and the variable progress after to have reached 1.0 return to 0.75 and then return to 1.0 How can I solve?
Thank you and sorry again for the incorrect error report.

**Comment by CPiersigilli** [comment]
You can see what I reported in the post above by downloading the XCODE 9 file [here](https://my.pcloud.com/publink/show?code=XZfcou7ZyLGgiTfTYCFjRcOWkvI3RuwUiBG7) and pressing the `Upload File` button from the application.

**Comment by amosavian** [comment]
Hi i missed that.
Would you mind open a separate issue?
